# [tool.black]
# line-length = 100

# [tool.isort]
# profile = "black"
# line_length = 100

# [tool.pylint.messages_control]
# disable = [ "missing-class-docstring",
#         "consider-using-f-string",
#         "import-error",
#         "missing-function-docstring"]
[tool.ruff]
line-length = 100